/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Files: typeof import('./src/components/upload/Files.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    GoBack: typeof import('./src/components/button/GoBack.vue')['default']
    GroupSetting: typeof import('./src/components/button/GroupSetting.vue')['default']
    Image: typeof import('./src/components/upload/Image.vue')['default']
    Locale: typeof import('./src/components/button/Locale.vue')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/button/Theme.vue')['default']
    User: typeof import('./src/components/button/User.vue')['default']
  }
}
